### GET Todos
GET http://localhost:9999/api/todos

### GET Todos by ID
GET http://localhost:9999/api/todos/2

### Create Todos
POST http://localhost:9999/api/todos 
Content-Type: application/json

{
    "user_id": 1234,
    "title": "Go to work",
    "priority": "B",
    "status": "READY",
    "completion_level": 0
}

### Update Todos
PUT http://localhost:9999/api/todos 
Content-Type: application/json

{
    "id": 8,
    "title": "Go to work2222",
    "priority": "A",
    "status": "DOING",
    "completion_level": 50
}

### Delete Todos
DELETE http://localhost:9999/api/todos/3
